
spring.datasource.url=jdbc:postgresql://localhost:5432/yagodkaDB
spring.datasource.username=postgres
spring.datasource.password=Admin
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.mvc.view.prefix = /WEB-INF/jsp/
spring.mvc.view.suffix = .jsp








# Database configuration
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/yagodkaDB
jdbc.username=postgres
jdbc.password=Admin

# Token configuration
token.secret=mysecretkey
token.expiration=3600000 # 1 hour in milliseconds
